export const GROUND_DISPLAY = 'GROUND_DISPLAY';
export const GROUND_DISPLAY_SUCCESS = 'GROUND_DISPLAY_SUCCESS';
export const GROUND_DISPLAY_FAILURE = 'GROUND_DISPLAY_FAILURE';
export const TEAM_VIEW = 'TEAM_VIEW';
export const TEAM_VIEW_SUCCESS = 'TEAM_VIEW_SUCCESS';
export const TEAM_VIEW_FAILURE = 'TEAM_VIEW_FAILURE';
export const GROUND_VIEW_TEAMNAME = 'GROUND_VIEW_TEAMNAME';
