/* GROUND DISPLAY SECTION */
export const GROUND_DISPLAY = 'GROUND_DISPLAY';
export const GROUND_DISPLAY_SUCCESS = 'GROUND_DISPLAY_SUCCESS';
export const GROUND_DISPLAY_FAILURE = 'GROUND_DISPLAY_FAILURE';
/* HOME SECTION */
export const TEAM_VIEW = 'TEAM_VIEW';
export const TEAM_VIEW_SUCCESS = 'TEAM_VIEW_SUCCESS';
export const TEAM_VIEW_FAILURE = 'TEAM_VIEW_FAILURE';
/* CLICKED TEAM NAME SECTION */
export const GROUND_VIEW_TEAMNAME = 'GROUND_VIEW_TEAMNAME';
/* AUTHENTICATION SECTION */
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
