/* GROUND DISPLAY SECTION */
export const GROUND_DISPLAY = 'GROUND_DISPLAY';
export const GROUND_DISPLAY_SUCCESS = 'GROUND_DISPLAY_SUCCESS';
export const GROUND_DISPLAY_FAILURE = 'GROUND_DISPLAY_FAILURE';
/* HOME SECTION */
export const TEAM_VIEW = 'TEAM_VIEW';
export const TEAM_VIEW_SUCCESS = 'TEAM_VIEW_SUCCESS';
export const TEAM_VIEW_FAILURE = 'TEAM_VIEW_FAILURE';
/* CLICKED TEAM NAME SECTION */
export const GROUND_VIEW_TEAMNAME = 'GROUND_VIEW_TEAMNAME';
/* AUTHENTICATION SECTION */
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
/* GET USER STATUS SECTION */
export const AUTH_GET_STATUS = 'AUTH_GET_STATUS';
export const AUTH_GET_STATUS_SUCCESS = 'AUTH_GET_STATUS_SUCCESS';
export const AUTH_GET_STATUS_FAILURE = 'AUTH_GET_STATUS_FAILURE';
/* GAME REGISTER SECTION */
export const GAME_REGISTER = 'GAME_REGISTER';
export const GAME_REGISTER_SUCCESS = 'GAME_REGISTER_SUCCESS';
export const GAME_REGISTER_FAILURE = 'GAME_REGISTER_FAILURE';
